name: codex
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/java.png
    - images/csharp.png
    - images/dart.png
    - images/c.jpg
    - images/flutter.png
    - images/asp.net.jpg
    - images/spring-framework.png
    - images/hibernate.png
    - images/sqlserver.png
    - images/mongodb.png
    - images/MySQL.png
    - images/Msaccess.png
    - images/vscode.jpg
    - images/ms-visual-studio.jpg
    - images/mongodb-compass.png
    - images/git.png